const data = JSON.stringify(
  {
    dependencies: {
      "@generouted/react-router": "^1.18.2",
      "@hookform/resolvers": "^3.3.4",
      "@nanostores/react": "^0.7.1",
      clsx: "^2.1.0",
      nanostores: "^0.9.5",
      react: "^18.2.0",
      "react-dom": "^18.2.0",
      "react-hook-form": "^7.49.3",
      "react-icons": "^5.0.1",
      "react-router-dom": "^6.21.3",
      "tailwind-merge": "^2.2.1",
      zod: "^3.22.4",
    },
    devDependencies: {
      "@types/node": "^20.11.6",
      "@types/react": "^18.2.43",
      "@types/react-dom": "^18.2.17",
      "@typescript-eslint/eslint-plugin": "^6.14.0",
      "@typescript-eslint/parser": "^6.14.0",
      "@vitejs/plugin-react": "^4.2.1",
      autoprefixer: "^10.4.17",
      daisyui: "^4.6.0",
      eslint: "^8.55.0",
      "eslint-plugin-react-hooks": "^4.6.0",
      "eslint-plugin-react-refresh": "^0.4.5",
      postcss: "^8.4.33",
      prettier: "^3.2.4",
      tailwindcss: "^3.4.1",
      typescript: "^5.2.2",
      vite: "^5.0.8",
    },
  },
  null,
  2,
);

export default data;
